spring:
  security:
    oauth2:
      client:
        registration:
          lsso-client-oidc:
            provider:
            client-id:
            client-secret:
            authorization-grant-type:
            redirect-uri:
            scope:
            client-name:
          lsso-client-authorization-code:
            provider:
            client-id:
            client-secret:
            scope:
            authorization-grant-type:
            redirect-uri:
            client-name:
        provider:
          spring:
            authorization-uri:
            token-uri:
            user-info-uri:
            jwk-set-uri:
  thymeleaf:
    cache: false
  devtools:
    livereload:
      port: 35729

server:
  port: 8082
  servlet:
    context-path: /lsso-client

logging:
  level:
    org.springframework: INFO

resourceserver:
  api:
    project:
      url: http://localhost:8081/lsso-resource-server/api/projects/